# Generated by Django 2.1.7 on 2019-03-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_version', models.IntegerField(max_length=10)),
                ('minor_version', models.IntegerField(max_length=10)),
                ('device_id', models.IntegerField(max_length=10)),
                ('hidden_flag', models.IntegerField(default=0, max_length=1)),
                ('tag', models.CharField(default=None, max_length=255, null=True)),
                ('en', models.TextField(default=None, max_length=65535, null=True)),
                ('ru', models.TextField(default=None, max_length=65535, null=True)),
            ],
            options={
                'db_table': 'device_firmware',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='ImageVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(max_length=10)),
                ('value', models.CharField(max_length=200)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='image', to='recipes.Images')),
            ],
            options={
                'db_table': 'image_variants',
            },
        ),
    ]
